/// Lista fixa dos setores que devem ser auditados. Usada tanto no
/// seletor de "Área/Seção Auditada" quanto no checklist de pendências
/// por mês na tela de Indicadores.
const List<String> auditSectors = [
  'Repuxo',
  'Recebimento',
  'MTG Hera',
  'MKT',
  'Manutenção ADM',
  'Almoxarifado',
  'Teste Titan',
  'Área Externa',
  'Metálicos',
  'Leves',
  'Eng. Produto',
  'Tubos',
  'Manutenção Fab',
  'RH',
  'Laser',
  'Balanceamento',
  'Resíduos',
  'Dobra',
  'Solda',
  'QA',
  'Pintura',
  'P&D',
  'Financeiro',
  'ADM Vendas',
  'MTG Voluta',
  'Serralheria',
  'CL',
  'Processos',
  'PCP',
  'SST',
  'TI',
];
