/// Lista fixa dos setores/áreas que devem ser auditados todo mês.
/// Usada na tela de Indicadores para mostrar o que ainda falta auditar.
const List<String> setoresAuditaveis = [
  'Repuxo',
  'Recebimento',
  'MTG Hera',
  'MKT',
  'Manutenção ADM',
  'Almoxarifado',
  'Teste Titan',
  'Área Externa',
  'Metálicos',
  'Leves',
  'Eng. Produto',
  'Tubos',
  'Manutenção Fab',
  'RH',
  'Laser',
  'Balanceamento',
  'Resíduos',
  'Dobra',
  'Solda',
  'QA',
  'Pintura',
  'P&D',
  'Financeiro',
  'ADM Vendas',
  'MTG Voluta',
  'Serralheria',
  'CL',
  'Processos',
  'PCP',
  'SST',
  'TI',
];
